# Grafana 데이터 저장용 PersistentVolume
# hostPath 는 권장하는 volume 이 아님에 유의, 필요 시 volume 만 변경하여 사용하길 권장함
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef: # for reserved volume: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
    name: grafana-pvc
    namespace: monitoring
  hostPath:
    path: ${GRAFANA_DATA_PATH}  # apply-to-k8s.sh에서 치환됨
    type: DirectoryOrCreate
---
# Grafana용 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: "" # dynamic provisioning을 사용하지 않음: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi