apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        # loki 구동 후 특정 시점 이후 로그가 사라지는 이상 현상이 발생되고 있음, 따라서 해당 이슈가 없는 버전을 사용한다.
        # ref: "https://github.com/grafana/loki/issues/10529#issuecomment-1715632419"
        image: grafana/loki:2.8.4
        ports:
        - containerPort: 3100
          name: http
        args:
        - -config.file=/etc/loki/local-config.yaml
        volumeMounts:
        - name: loki-storage
          mountPath: /loki
        - name: loki-config
          mountPath: /etc/loki
      volumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: loki-pvc
      - name: loki-config
        configMap:
          name: loki-config