apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  # Kubernetes Service Discovery를 통해 내부에서 'loki:3100'으로 접근 가능
  # 같은 네임스페이스의 Pod들은 서비스명만으로 통신 가능
  # 전체 도메인: loki.monitoring.svc.cluster.local
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    nodePort: 32102
    protocol: TCP
    name: http
  type: NodePort