# Jenkins Service
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  # Prometheus 모니터링을 위한 어노테이션
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000