# Jenkins 데이터 저장용 PersistentVolume
# hostPath 는 권장하는 volume 이 아님에 유의, 필요 시 volume 만 변경하여 사용하길 권장함
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # 데이터 유지를 위한 설정: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain
  storageClassName: ""
  claimRef: # for reserved volume: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
    name: jenkins-pvc
    namespace: devops-tools
  hostPath:
    path: ${JENKINS_DATA_PATH}  # apply-to-k8s.sh에서 치환됨
    type: DirectoryOrCreate
---
# Jenkins용 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops-tools
spec:
  storageClassName: "" # dynamic provisioning을 사용하지 않음: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi