kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
# Jenkins용 PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-hostpath
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /PATH/TO/BE/REPLACED/BY/SCRIPT  # apply-to-k8s.sh 스크립트가 동적으로 설정함
    type: DirectoryOrCreate

---
# Jenkins용 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi